config/routes.rb
Rails.application.routes.draw do
  
  resources :gossips
  resources :users
  resources :cities
  resources :gossips do
    resources :comments, only: [:new, :create, :index, :destroy]
  end
  resources :sessions, only: [:new, :create, :destroy]

  get '/', to: 'gossips#index'
  get '/static/team', to: 'static#team'
  get '/static/contact', to: 'static#contact'
  post '/gossips/:id/comments', to: "comments#create", as:"gossips_comment_create"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @id = params[:id]
    @city_gossips = City.find(@id).gossips
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @id = params[:id]
    @comment = Comment.create(content: params[:content], author_id: current_user.id, gossip_id: params[:gossip_id])
    redirect_to gossip_path(params[:gossip_id])

  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:index, :new, :edit]
  before_action :authenticate_current_user, only: [:update, :destroy, :edit]
  def index
    @gossip = Gossip.all
    @gossip = Gossip.new
    
  end

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

  def authenticate_current_user
    @gossips = Gossip.find(params[:id])
    if current_user.id == @gossips.user.id
      puts 'yey'
    else
      redirect_to gossips_path
      puts 'oh no'
    end
  end

  def new
    @gossip = Gossip.new
  end

  def show
    @id = params[:id]
  end

  def edit
    @id = params[:id]
    @gossips = Gossip.find(params[:id])
    puts @gossips.id
    puts current_user.id
  end

  def update
    @gossips = Gossip.find(params[:id])
    post_params = params.require(:gossip).permit(:title, :content)
    @gossips.update(post_params)
    redirect_to gossips_path
  end 

  def create
    @gossip = Gossip.new(post_params)
    @gossip.user_id = current_user.id
    p @gossip
    if @gossip.save
      render "index", :notice => "User saved"
    else
      render "new", :alert => 'Alert message!'
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
  end

  private
  def post_params
    params.permit(:title, :content)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    puts "Session "
    @user = User.find_by(email: params[:email])

    if @user && @user.authenticate(params[:password])
      log_in(@user)
      redirect_to gossips_path
      puts "hello"
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
      puts "bye bye"
    end
    
  end

  def destroy
    session.delete(:user_id)
    render 'new'
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def team
    puts "Salut, je suis dans le serveur"

    puts "$" * 60 #ça affiche une ligne de 60 symboles $ facilement visible dans le terminal
    puts params #tu sais que params doit s'afficher entre les 2
    puts "$" * 60
  end

  def contact
    puts "Salut, je suis dans le serveur"

    puts "$" * 60 #ça affiche une ligne de 60 symboles $ facilement visible dans le terminal
    puts params #tu sais que params doit s'afficher entre les 2
    puts "$" * 60
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @id = params[:id]
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      age: params[:age],
      description: params[:description],
      email: params[:email], 
      password: params[:password],
      city_id: City.all.sample
    )
    p @user
    
    if @user.save
      redirect_to gossips_path, :notice => "User saved"
    else
      render "new", :alert => 'Alert message!'
    end
    p Rails.logger.info(@user.errors.inspect) 
  end

end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/show.html.erb
<div class="div_text_centered">
  <h2>City</h2>
    <p><%= City.find(@id).name %></p><br/>

<div class="row">
  <%@city_gossips.each do |gossip| %>
    <div class="col-sm-4 mx_auto">
      <div class="card text-center">
        <div class="card-body">
          <p class="card-text"><%= gossip.content%></p>
          <p class="card-text"><%= gossip.user.first_name%>  <%= gossip.user.last_name%></p>
        </div>
      </div>
      <br/>
    </div>
  <% end %>
</div>


</div>

app/views/gossips/edit.html.erb
<h1>Editer le gossip</h1>

<%= form_for @gossips do |f|%>

  <div class ="form_group">
    <label>Titre du Gossip</label>
    <%= f.text_field :title, class: 'form-control'%>
  </div>
<br>
  <div class ="form_group">
    <label>Gossip</label>
    <%= f.text_area :content, class: 'form-control'%>
  </div>
<br>
  <div class ="form_group">
    <button type="submit" class="btn btn-primary">Modifier le Gossip </button>
    </div>

<% end%>

app/views/gossips/index.html.erb
<% if @gossip.save %>
<div class="alert alert-success" role="alert">
  <p>Le message est bien enregistré</p>
  </div>
<% end %> 


<h2 class="h1_welcome"><%= "Welcome #{current_user.first_name} "%></h2>

<h1 class="h1_welcome">Here you can see all the Gossips!</h1>
<h3 class="h1_welcome"><%= "Today you can find #{@gossip_count} gossips" %></h3>
<hr>

<div class="row">
  <% Gossip.all.sort.each_with_index do |gossip, index|  %>
    <div class="col-sm-4">
      <div class="card text-center">
        <div class="card-body">
          <h5 class="card-title"><%= gossip.title %></h5>
          <p class="card-text"><%= gossip.user.first_name %></p>
          <%= link_to "Gossip n°#{gossip.id}", gossip_path(gossip.id), class:"btn btn-primary" %>
        </div>
      </div>
      <br/>
    </div>
  <% end %>
</div>

app/views/gossips/new.html.erb
<% if @gossip.errors.any? %>
  <div class="alert alert-danger" role="alert">Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</div>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>

<% end %>

<!--Cette page va contenir notre form pour faire NEW et CREATE-->
<div class="div_text_centered">
<h2>Create here your new juicy gossip !</h2>
<%= form_tag url_for(action: 'create'), method: "post" do %>

  <h4><%= label_tag 'Title' %></h4>
  <%= text_field_tag 'title'%>
  <br /> <br />

  <h4><%= label_tag 'Content' %></h4>
  <%= text_area_tag 'content'%>
  <br /> <br />

  <%= submit_tag "Create Post", {class: "btn btn-primary"} %>
  <br><br>
<% end %>

</div>

<!--https://launchschool.com/books/demystifying_rails/read/form_helpers#formtag -->

app/views/gossips/show.html.erb
<div class="div_text_centered">
  <h2>Gossiper</h2>
    <p><%= Gossip.find(@id).user.first_name %></p><br/>
  <h3>Title</h3>
    <p><%= Gossip.find(@id).title %></p><br/>
  <h4>Contenu</h4>
    <p><%= Gossip.find(@id).content %></p><br/>
  <h5>Publishing Date</h5>
    <p><%= Gossip.find(@id).created_at %></p><br/>

  <%= link_to "Who is Gossiper #{Gossip.find(@id).user.first_name}?", user_path(Gossip.find(@id).user.id), class:"btn btn-primary" %>
  
  <%if current_user.id == Gossip.find(@id).user.id%>
    <%= link_to "Edit the Gossip", edit_gossip_path(Gossip.find(@id).id), class:"btn btn-secondary" %>
    <%= link_to "Supprimer le Gossip", gossip_path(Gossip.find(@id).id), class:"btn btn-danger",  data: {confirm: 'Etes-vous sur?'}, method:"DELETE"%>
  <%end%>
  <hr>

</div>

<h2>Comments section</h2>
<div class="row">
  <% Gossip.find(@id).comments.each do |comment|  %>
    <div class="col-sm-4">
      <div class="card text-center">
        <div class="card-body">
          <h5 class="card-title"><%= comment.author.first_name%> <%= comment.author.last_name%></h5>
          <p class="card-text"><%= comment.content %></p>
        </div>
      </div>
      <br/>
    </div>
  <% end %>
</div>

<div>
  <form action= <%= gossips_comment_create_path %> method="POST" >
    <div class ="form-group">
      <label for="exampleInputEmail1">Add a comment !</label>
      <input type="hidden" name="authenticity_token" placeholder="Your comment" value="<%= form_authenticity_token %>">
      <input type="text" id="content" name="content" class="form-control">
      <input type="hidden" id="gossip_id" value="@id">
    </div>
  <input type="submit" value="Valider" class ="btn btn-secondary">
  </form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Gossip Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <<a class="navbar-brand" href="https://www.thehackingproject.org">THP</a>>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Home", gossips_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", static_contact_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Team", static_team_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New Gossip", new_gossip_path, class: "nav-link disable" %>
          </li>                  
        </ul>
        <ul class="navbar-nav mr-left">
        <%if current_user == nil %>
          <li class="nav-item">
            <%= link_to "S'inscrire", new_user_path, class: "nav-link disable" %>
          </li>
          <li class="nav-item">
            <%= link_to "Se connecter", new_session_path, class: "nav-link disable" %>
          </li>
          <%else%>
          <li class="nav-item">
            <%= link_to "Se déconnecter", session_path(session.id), method: :delete, class: "nav-link disable" %>
          </li>
          <%end%>
        </ul>

      </div>
    </nav>

    <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3 h1_jumbo">Welcome to The Gossip Project !</h1>
          
        
        </div>
      </div>

      <%= yield %>  

      </div> 
    </main>

    <footer class="footer div_text_centered">
      <p>&copy; Nicolas - Karine  2022</p>
    </footer>

  </body>
</html>

app/views/users/new.html.erb
<div class="div_text_centered">
<h2>Création d'un user !</h2>
<%= form_tag url_for(action: 'create'), method: "post" do %>

<h4><%= label_tag 'Email' %></h4>
  <%= text_field_tag 'email'%>
  <br /> <br />

<h4><%= label_tag 'First name' %></h4>
  <%= text_field_tag 'first_name'%>
  <br /> <br />

<h4><%= label_tag 'Last name' %></h4>
  <%= text_field_tag 'last_name'%>
  <br /> <br />

<h4><%= label_tag 'Age' %></h4>
  <%= text_field_tag 'age'%>
  <br /> <br />

<h4><%= label_tag 'Description' %></h4>
  <%= text_field_tag 'description'%>
  <br /> <br />

<h4><%= label_tag 'Password' %></h4>
  <%= password_field_tag 'password'%>
  <br /> <br />

  <%= submit_tag "Create User", {class: "btn btn-primary"} %>
  <br><br>
<% end %>

</div>

app/views/users/show.html.erb
<div class="div_text_centered">

  <h2>Gossiper's first name</h2>
    <p><%= User.all.find_by(id: @id).first_name %></p><br/>
  <h2>Gossiper's last name</h2>
    <p><%= User.find(@id).last_name  %></p><br/>
  <h2>Gossiper's age</h2>
    <p><%= User.find(@id).age %></p><br/>
  <h2>Description of the Rumor</h2>
    <p><%= User.find(@id).description %></p><br/>
  <h2>Gossiper's email</h2>
    <p><%= User.find(@id).email %></p><br/>
  <h2>Gossiper's city</h2>
    <p><%= User.find(@id).city.name %></p><br/>

  <%= link_to "City of #{User.all.find_by(id: @id).first_name}", city_path(User.find(@id).city.id), class:"btn btn-primary" %>

  <hr>
</div>